- name: configure the db serice 
  hosts: db
  decome: yes 
  vars: 
  mysql_passwd:  ExpenseApp@1
  taskes:
    - name: install the mysql server 
      ansible.builtin.dnf:
        name: mysql-server
        state: installed
    
