- name: install nginx 
  hosts: one 
  become: yes 
  tasks: 
    - name: install nginx 
      ansible.builtin.dnf:
        name: nginx 
        state: installed 
    - name: enable and start the nginx 
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

